global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: WARN

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      middlewares:
        - rate-limit@file
      tls:
        options: modern@file

certificatesResolvers:
  cloudflare:
    acme:
      email: "${TRAEFIK_EMAIL}"
      storage: /certs/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  file:
    filename: /dynamic.yml
    watch: true
